#!/usr/bin/env python3
"""
Send a pinned onboarding message to the TrendRider Telegram channel.
One-time script — run once, then delete or archive.
"""

import json
import os
import sys

import requests

FT_HOME = os.environ.get(
    "FT_HOME", os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)
CONFIG_PATH = os.getenv("FT_CONFIG_PATH", os.path.join(FT_HOME, "config.json"))

SHEETS_URL = (
    "https://docs.google.com/spreadsheets/d/"
    "1ZWRJ0PcBSk910MZv426PrleriBnInykr3OebWXJPm-g"
)


def get_telegram_config() -> tuple:
    """Return (token, chat_id) from env vars or Freqtrade config.json."""
    token = os.getenv("TG_TOKEN")
    chat_id = os.getenv("TG_CHAT_ID")
    if token and chat_id:
        return token, chat_id
    try:
        with open(CONFIG_PATH, "r", encoding="utf-8") as f:
            cfg = json.load(f)
        tg = cfg.get("telegram", {})
        return tg["token"], str(tg["chat_id"])
    except (FileNotFoundError, KeyError) as exc:
        sys.exit(f"Cannot read Telegram credentials: {exc}")


ONBOARDING_TEXT = """
*Welcome to TrendRider Signals* 🚀

Automated crypto trading signals powered by an algorithmic strategy.
Every signal is generated by code — no emotions, no guesswork.

━━━━━━━━━━━━━━━━━━━━━━

*📡 How to read signals*

Each signal contains:

• *Entry Zone* — price range to open the position
• *Stop Loss (SL)* — exit if price goes against you
• *TP1 / TP2 / TP3* — take-profit targets (scale out)
• *Confidence* — signal strength (1-10 scale)
• *Setup* — type of trade (Trend / Reversal / Breakout)

_Example:_
```
LONG BTC/USDT
Entry: 64 200 – 64 500
SL: 63 100
TP1: 65 800  TP2: 67 000  TP3: 69 500
Confidence: 8/10 | Setup: Trend
```

━━━━━━━━━━━━━━━━━━━━━━

*💰 Position Sizing Guide*

• Risk *1-2%* of your portfolio per trade
• Never allocate more than *5%* to a single position
• Use SL — always. No exceptions
• Scale out at TP levels (e.g. 40% at TP1, 30% at TP2, 30% at TP3)

━━━━━━━━━━━━━━━━━━━━━━

*🤖 Auto-Trading with Cornix*

Want signals executed automatically?

1\\. Add @cornix\\_trading\\_bot to your Telegram
2\\. Connect your Bybit account in Cornix
3\\. Subscribe Cornix to this channel
4\\. Cornix will auto-parse every signal and place orders

_No manual copying needed — fully hands-free\\._

━━━━━━━━━━━━━━━━━━━━━━

*📊 Track Record*

All trades are logged in our public Google Sheet:
[Open Performance Tracker]({sheets_url})

━━━━━━━━━━━━━━━━━━━━━━

*❓ FAQ*

*Is this financial advice?*
No\\. All signals are for *educational purposes only*\\.
You are solely responsible for your own trades\\.

*How many signals per week?*
Varies — quality over quantity\\. Typically 3-10/week
depending on market conditions\\.

*What pairs are traded?*
BTC, ETH, SOL, BNB on *Bybit Futures*\\.

*What timeframes?*
Primary: 1h\\. Confirmation: 5m and 4h\\.

━━━━━━━━━━━━━━━━━━━━━━

*Channel:* @TrendRiderSignals
*Strategy:* TrendRider v2\\.1

_Trade smart\\. Manage risk\\. Stay consistent\\._
""".strip().format(sheets_url=SHEETS_URL)


def send_message(token: str, chat_id: str, text: str) -> int:
    """Send a Markdown message and return the message_id."""
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    resp = requests.post(
        url,
        json={
            "chat_id": chat_id,
            "text": text,
            "parse_mode": "MarkdownV2",
            "disable_web_page_preview": True,
        },
        timeout=30,
    )
    data = resp.json()
    if not data.get("ok"):
        sys.exit(f"sendMessage failed: {data}")
    msg_id = data["result"]["message_id"]
    print(f"Message sent (id={msg_id})")
    return msg_id


def pin_message(token: str, chat_id: str, message_id: int) -> None:
    """Pin a message in the chat."""
    url = f"https://api.telegram.org/bot{token}/pinChatMessage"
    resp = requests.post(
        url,
        json={"chat_id": chat_id, "message_id": message_id},
        timeout=30,
    )
    data = resp.json()
    if not data.get("ok"):
        print(f"Warning: pinChatMessage failed: {data}")
    else:
        print("Message pinned successfully")


def main() -> None:
    token, chat_id = get_telegram_config()
    print(f"Sending onboarding message to chat {chat_id}...")
    msg_id = send_message(token, chat_id, ONBOARDING_TEXT)
    pin_message(token, chat_id, msg_id)
    print("Done!")


if __name__ == "__main__":
    main()
