import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — TrendRider",
  description: "Terms of Service for TrendRider algorithmic crypto trading signals.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-4 py-20">
        <a href="/" className="text-primary text-sm hover:underline mb-8 inline-block">&larr; Back to home</a>
        <h1 className="text-4xl font-bold mb-8 gradient-text">Terms of Service</h1>
        <p className="text-muted text-sm mb-12">Last updated: March 22, 2026</p>

        <div className="prose prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted leading-relaxed text-sm">
              By accessing or using TrendRider (&ldquo;the Service&rdquo;), including our Telegram channel, website, and any associated tools, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Nature of the Service</h2>
            <p className="text-muted leading-relaxed text-sm">
              TrendRider provides algorithmic trading signals for informational and educational purposes only. The signals are generated by automated algorithms and should not be considered financial, investment, or trading advice. You are solely responsible for your trading decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. No Financial Advice</h2>
            <p className="text-muted leading-relaxed text-sm">
              TrendRider is not a registered investment advisor, broker-dealer, or financial planner. All information provided is for educational purposes. Past performance is not indicative of future results. Trading cryptocurrencies involves substantial risk of loss.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Risk Disclosure</h2>
            <p className="text-muted leading-relaxed text-sm">
              Cryptocurrency trading carries a high level of risk and may not be suitable for all investors. You should carefully consider your investment objectives, level of experience, and risk appetite before trading. Never invest more than you can afford to lose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. Subscription & Payments</h2>
            <p className="text-muted leading-relaxed text-sm">
              Paid subscriptions (Basic, VIP) are billed monthly. You may cancel at any time. No refunds are provided for partial months. The free tier provides delayed signals and does not require payment.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Intellectual Property</h2>
            <p className="text-muted leading-relaxed text-sm">
              All content, algorithms, signals, and branding are the intellectual property of TrendRider. You may not redistribute, resell, or share paid signals without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Limitation of Liability</h2>
            <p className="text-muted leading-relaxed text-sm">
              TrendRider shall not be liable for any direct, indirect, incidental, consequential, or exemplary damages arising from the use of the Service, including but not limited to financial losses from trading activities.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Modifications</h2>
            <p className="text-muted leading-relaxed text-sm">
              We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. Contact</h2>
            <p className="text-muted leading-relaxed text-sm">
              For questions about these Terms, contact us at{" "}
              <a href="mailto:support@trendrider.net" className="text-primary hover:underline">support@trendrider.net</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
